### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#30]
1. Есть возможность задать максимальное значение равное минимальному и наоборот. При этом слайдер ломается:
![NaN](https://user-images.githubusercontent.com/85496220/123958128-5c8d3c80-d9b5-11eb-9512-abc2df8a6f5f.gif)

2. Задав большой диапазон значений при маленьком шаге, можно сломать шкалу. А ещё при этом браузер начинает подвисать) Количество меток шкалы лучше ограничить 5 - 20, все отображать не стоит.
![100000](https://user-images.githubusercontent.com/85496220/123958652-f8b74380-d9b5-11eb-8156-bb6a1acb93bc.gif)

3. При изменении параметров слайдера значение ползунка и подсказки не обновляются:
![changeMin](https://user-images.githubusercontent.com/85496220/123959690-1cc75480-d9b7-11eb-90cf-4d0e343a3134.gif)

4. Значение шага лучше ограничить, чтобы он не превышал диапазон значений слайдера:
![step1000](https://user-images.githubusercontent.com/85496220/123959910-5f892c80-d9b7-11eb-92b8-543495444642.gif)

5. При значении max не кратном шагу метки шкалы не совпадают с положением ползунка:
![1001](https://user-images.githubusercontent.com/85496220/123961139-b7746300-d9b8-11eb-8f36-7302d08ff8fc.gif)

**Comment by webproject67** [comment]
[#30](https://github.com/webproject67/Slider/issues/30) [updated](https://github.com/webproject67/Slider/commit/381cdf7e121746b0003f16973d46560f87eb3ebc)

**Comment by romansilivestrov** [comment]
6. Если последний шаг "укороченный", положения ползунка и курсора расходятся:
![last_step](https://user-images.githubusercontent.com/85496220/126627219-ce1251d9-c2cf-4b36-8161-cc83db5a1adf.gif)

**Comment by webproject67** [comment]
[#30](https://github.com/webproject67/Slider/issues/30) [updated](https://github.com/webproject67/Slider/pull/44)

**Comment by romansilivestrov** [comment]
До сих пор отличается от "полных" шагов - переключается не посередине, а на самом шаге. Если неполный шаг больше половины полного, получается интересное поведение:
![lastStep](https://user-images.githubusercontent.com/85496220/127150072-e8cec88f-db48-4946-bf63-a3b4e75b81cb.gif)

**Comment by webproject67** [comment]
[#30](https://github.com/webproject67/Slider/issues/30) [updated](https://github.com/webproject67/Slider/pull/51)
