### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#31]
Архитектура MVP подразумевает разделение приложения на слои: модель работает с бизнес-логикой, вьюха отображает данные модели и принимает ввод пользователя, а презентер - связующее звено между ними. Сейчас у тебя вся логика находится в классе `SliderPresenter` - надо разнести её по соответствующим слоям. Для оповещения об изменениях значений/конфигов в инстансах классов можно использовать паттерн [Наблюдатель (Observer)](https://refactoring.guru/ru/design-patterns/observer/typescript/example).

**Comment by webproject67** [comment]
[#31](https://github.com/webproject67/Slider/issues/31) [updated](https://github.com/webproject67/Slider/pull/34)

**Comment by romansilivestrov** [comment]
Бизнес логика (значения ползунков и методы для работы с ними, которые должны быть в модели) всё ещё в презентере.

Что касается последних изменений - метод `handleFlagMouseDown` сейчас повторяется в нескольких файлах без существенных отличий. Я так понимаю, что flag-one, flag-range и т.д. - это бегунки для разных настроек слайдера? Если различия между ними только в шаблонах, возможно, стоит их объединить в один класс? Возможно, не только их?)

Функции, определяемые в `handleFlagMouseDown` (и подобных местах) лучше вынести в отдельные методы.

Не вижу классов для трека и прогресс-бара (возможно, такого требования по разделению вьюх не было, когда ты приступал к заданию - тогда добавлять не обязательно).

**Comment by webproject67** [comment]
[#31](https://github.com/webproject67/Slider/issues/31) [updated](https://github.com/webproject67/Slider/pull/35)

**Comment by romansilivestrov** [comment]
Сейчас выглядит гораздо лучше, только зачем View создаёт новую модель, когда она уже определена в презентере? Также вид не должен обращаться к свойствам модели напрямую (`this.model.state`). Вид не должен знать о модели и тем более создавать её, это повышает связанность слоёв.

По заданию вид и модель не знают друг о друге, знать о других слоях может только презентер. Он:
- реагирует на сообщения от отображения о действиях пользователей и обновляет модель;
- реагирует на сообщения об обновлении модели и обновляет отображение.

**Comment by webproject67** [comment]
[#31](https://github.com/webproject67/Slider/issues/31) [updated](https://github.com/webproject67/Slider/pull/40)

**Comment by romansilivestrov** [comment]
1. >По заданию вид и модель не знают друг о друге, знать о других слоях может только презентер.

   Сейчас модель и вид, насколько я вижу, подписаны друг на друга напрямую.

2. До сих пор слишком много логики во view:
![image](https://user-images.githubusercontent.com/85496220/126627693-4fd168c5-1db3-4bbc-af5f-9c0139d5efa0.png)
подобные проверки скорее стоит перенести в модель.

3. В ТЗ есть пункт "возможность на лету изменить значение "снаружи" javascript-ом". То есть должно быть навроде такого:
```js
$mySlider = $('#my-slider').slider({});
$mySlider.slider('config'); // узнать настройки
$mySlider.slider('config', { min, max }); // задать настройки
```
Т. е. при создании слайдера плагин возвращает объект (паттерн фасад), позволяющий менять настройки/значения.

4. Я так понял, ConfiguringView - это панель настроек и она всегда рендерится вместе со слайдером. Так как панель нужна только для демонстрации, в "реальных" условиях использования плагина её отображать не нужно. Она скорее должна быть внешним модулем, который как раз общается с "фасадом" инстанса слайдера.

**Comment by webproject67** [comment]
[#31](https://github.com/webproject67/Slider/issues/31) [updated](https://github.com/webproject67/Slider/pull/48)
