### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#32]
![image](https://user-images.githubusercontent.com/85496220/124502441-2ba17300-ddcc-11eb-9744-1e342bed337f.png)

В typescript нижнее подчёркивание добавлять ни к чему, на видимость метода уже указвает модификатор private.

**Comment by romansilivestrov** [comment]
В `slider-presenter.ts` конструктор [перегружен](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.12). В таких случаях стоит их объединить в один или несколько служебных методов, в самом простом случае получится:

```js
constructor(main, state) {
  this.init(main, state);
}
```

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/124506024-7a064000-ddd3-11eb-85da-06f84f53abfe.png)

Не стоит задавать сложные типы / интерфейсы в месте использования, лучше подобное выносить:

```ts
type State = {...}
constructor (main: HTMLElement, state: State) {...}
```

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/124510453-7f1bbd00-dddc-11eb-85c4-fdad1934eae7.png)

От `any` надо бы избавиться. Вот [статейка](https://freshman.tech/snippets/typescript/fix-value-not-exist-eventtarget/) про типизацию событий.

**Comment by webproject67** [comment]
[#32](https://github.com/webproject67/Slider/issues/32) [updated](https://github.com/webproject67/Slider/pull/33)

**Comment by romansilivestrov** [comment]
1. `model` & `view` инициализируются в конструкторе, соответственно definite assignment assertion modifier (восклицательный знак) не обязателен. Его вообще лучше лишний раз не использовать.
![image](https://user-images.githubusercontent.com/85496220/126614308-911fb894-0f8f-4ac3-8462-1310c00f451f.png)

2. Метод `init` презентера вызывается единственный раз, при его инициализации. Для упрощения (`new Presenter(...)` вместо `new Presenter(...).init()`) лучше сделать метод приватным и перенести его вызов в конструктор.

3. В подобных местах функции лучше выносить:
![image](https://user-images.githubusercontent.com/85496220/126617031-a2290945-0b3d-4e7a-ae9f-09688873c8c9.png)
```ts
const callback = (keys, values) => {
  this.model.setValue(keys, values);
};
this.view.subscribe(callback);
```

**Comment by romansilivestrov** [comment]
С большой буквы принято именовать классы и конструкторы, переменные / константы обычно называют используя camelCase / капсом:
![image](https://user-images.githubusercontent.com/85496220/127154990-cfb70421-232c-4b88-a6a7-14b8f9a1ca75.png)
Для названий ключей объектов лучше тоже использовать camelCase.

**Comment by webproject67** [comment]
const «жёстко закодированы», а не конкретное значение.
[#32](https://github.com/webproject67/Slider/issues/32) [updated](https://github.com/webproject67/Slider/pull/52)

**Comment by romansilivestrov** [comment]
В шаблонах есть места, где отступы "сломаны":
![image](https://user-images.githubusercontent.com/85496220/127990842-9b930dd3-aacd-4f15-8b74-2c3ca85f8b92.png)

Лучше сделать как-нибудь так:
![image](https://user-images.githubusercontent.com/85496220/127990586-20f10256-ad80-48e9-a261-b2eaeaec83d2.png)

**Comment by romansilivestrov** [comment]
![image](https://user-images.githubusercontent.com/85496220/127991437-981940bc-3a24-40be-a99c-7ed2e4b264e4.png)
В таких местах неплохо бы [выносить условия](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.9)

**Comment by webproject67** [comment]
[#32](https://github.com/webproject67/Slider/issues/32) [updated](https://github.com/webproject67/Slider/pull/57)
