### ISSUE TITLE
README

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#36]
В README отсутствует описание использования плагина (создание слайдера, изменение настроек и значений).

**Comment by webproject67** [comment]
[#36](https://github.com/webproject67/Slider/issues/36) [updated](https://github.com/webproject67/Slider/pull/39)

**Comment by romansilivestrov** [comment]
И, пожалуйста, не надо писать всё заголовками :)

https://gist.github.com/Jekins/2bf2d0638163f1294637

**Comment by webproject67** [comment]
[#36](https://github.com/webproject67/Slider/issues/36) [updated](https://github.com/webproject67/Slider/pull/43)
