### ISSUE TITLE
Шкала значений

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#37]
На шкале отсутствуют значения меток:

![image](https://user-images.githubusercontent.com/85496220/126191812-fcc9b282-2b05-416a-8f33-de7c88b955bd.png)

**Comment by webproject67** [comment]
[#37](https://github.com/webproject67/Slider/issues/37) [updated](https://github.com/webproject67/Slider/pull/38)

**Comment by romansilivestrov** [comment]
![scale_mark](https://user-images.githubusercontent.com/85496220/126604601-ff81e50f-bd2f-47c7-80e5-d87ca366b762.gif)

**Comment by webproject67** [comment]
[#37](https://github.com/webproject67/Slider/issues/37) [updated](https://github.com/webproject67/Slider/pull/46)
