### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#41]
`@testing-library/dom` и `@testing-library/jest-dom` следует перенести в `devDependencies`.

**Comment by webproject67** [comment]
Airbnb ругает, оставлю в dependencies.
![11](https://user-images.githubusercontent.com/34152979/127033392-8eb8510e-e9e4-4e24-943e-7be712b7b136.PNG)

**Comment by romansilivestrov** [comment]
Это [настраивается](https://github.com/import-js/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md))

**Comment by webproject67** [comment]
удалил @testing-library/dom и @testing-library/jest-dom, по другому тестировал
[#41](https://github.com/webproject67/Slider/issues/41) [updated](https://github.com/webproject67/Slider/pull/54)
