### ISSUE TITLE
Использование плагина

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#50]
Не могу создать слайдер из консоли:
![image](https://user-images.githubusercontent.com/85496220/127152543-f5c2d951-6434-4bce-85ed-ac0e0b998886.png)

Демо страницу и jquery не стоит включать в bundle. Надо настроить вебпак так, чтобы можно было подключить собраный плагин на любую страницу:
```html
<script src="jquery-cdn-or-local-path" />
<script src="plugin-bundle" />
<script src="demo-script" />
```

**Comment by webproject67** [comment]
[#50](https://github.com/webproject67/Slider/issues/50) [updated](https://github.com/webproject67/Slider/pull/53)
