### ISSUE TITLE
webpack config

### ISSUE THREAD

**Issue by romansilivestrov** [webproject67/Slider#55]
terser-webpack-plugin нет в зависимостях; а если его установить - `npm run build` крашится:
![image](https://user-images.githubusercontent.com/85496220/127814887-718e2694-1b3b-4523-9e86-ae91d7557de7.png)

Повторяется секция:
![image](https://user-images.githubusercontent.com/85496220/127813725-323d958a-de4e-4d4b-acfb-bff725930125.png)

А jquery как вариант можно из `node_modules` подтянуть, чтобы не засорять `src`:
![image](https://user-images.githubusercontent.com/85496220/127815400-638c5ec7-de12-4121-918e-8fe099816a84.png)

**Comment by webproject67** [comment]
[#55](https://github.com/webproject67/Slider/issues/55) [updated](https://github.com/webproject67/Slider/pull/56)
