### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#60]
Сейчас в модели при ее обновлении в метод broadcast передается весь ее экземпляр, затем презентер передает этот экземпляр в вид, вследствие чего вид получает полный доступ к модели, у него появляется возможно вызывать ее методы и изменять ее состояние. Подобного быть не должно, вид в принципе нечего не должен знать о модели и не должен ни как с ней взаимодействовать. Вид должен только получать какие-то данные и уметь их отображать и оповещать если нужно обновить что-то передавая некое значение, в данном случае к примеру вид может вычислить процентное соотношение, насколько был перемещен бегунок относительно всей ширины слайдера, и модель уже будет решать подходит ли это соотношение ей или нет. Модель так же не должна нечего знать о виде, сейчас же в модели хранится информация об HTML элементе, по всей видимости об родительском.

**Comment by webproject67** [comment]
[#60](https://github.com/webproject67/Slider/issues/60) [updated](https://github.com/webproject67/Slider/pull/61)

**Comment by Azmodan95** [comment]
Сейчас модель просто используется для хранения данных, а все расчеты выполняет вид, по сути до этого было практически то же самое с той лишь разницей, что раньше вид вызывал методы модели для вычислений сейчас же эти методы переехали в вид.

Что должно быть:
1. В модели должны хранится данные относящиеся только к бизнес логике в данном случае это максимальный/минимальный диапазон, шаг, текущие значение и т.п., и модель должна производить вычисления только с ними. В модели не должно нечего быть связанного с отображением (координат, размеров и т.п.). 
2. Вид должен только отображать данные бизнес логики, и не должен производить ни каких с ними вычислений, он может производить только расчеты связанные с ним (с координатами, размерами и т.п.)
3. Презентер служит же связующим звеном между ними, и он единственный кто знает и о модели и виде. Он должен подписываться на обновления модели и вида, и при обновлении модели дергать соответствующие методы вида и наоборот.

**Comment by webproject67** [comment]
[#60](https://github.com/webproject67/Slider/issues/60) [update](https://github.com/webproject67/Slider/pull/66)

**Comment by Azmodan95** [comment]
Уже лучше. Но сейчас получается что модель знает о событиях вида, презентер сейчас передает данные которые, генерирует вид в модель, а в этих данных уже содержится информация о типе события. Не нужно подстраивать модель и вид друг под друга, для этого как раз и нужен презентер, модель и вид должны предоставлять интерфейс для обновления который нечего не знает об его окружении. К примеру в виде происходит перемещение бегунка и он генерирует событие, и модели об этом не нужно вообще нечего знать, этим должен заниматься презентер. Презентер знает как о события вида, так и событиях модели и он должен правильно реагировать в зависимости от того какое событие произошло и вызвать соответствующие методы в модели или виде. Соответственно события которые они генерируют должны быть основаны только на том что произошло, а не на том что должно произойти.

**Comment by webproject67** [comment]
[#60](https://github.com/webproject67/Slider/issues/60) [updated](https://github.com/webproject67/Slider/pull/70)
