### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#62]
Название файлов должно соответствовать тому что они экспортируют по умолчанию, то есть если из файла экспортируется класс Model, то и файл соответственно должен называться Model.ts.

**Comment by webproject67** [comment]
[#62](https://github.com/webproject67/Slider/issues/62) [updated](https://github.com/webproject67/Slider/pull/65)

**Comment by Azmodan95** [comment]
Один нюанс названия файлов должно полностью соответствовать тому что они экспортируют по умолчанию, к примеру класс называется CircleView, то файл тоже должен называться CircleView, а не Circle-view.

**Comment by webproject67** [comment]
Где то читал читал что название файла писать через дефис, а не camelCase, исправил
[#62](https://github.com/webproject67/Slider/issues/62) [updated](https://github.com/webproject67/Slider/pull/68)
