### ISSUE TITLE
Создание HTML элементов

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#63]
Сейчас все элементы создаются с помощью innerHTML, это приводит к тому что при каждом обновлении создаются новые dom узлы и для них повторно регистрируются события, чтобы обраться к этим элементам приходится использовать поиск по dom дереву, это все крайне не эффективно с точки зрения производительности. Для подобных случаев когда нам нужно активно взаимодействовать с созданными дом узлами лучше использовать createElement.

**Comment by webproject67** [comment]
Абстрактный класс не создает экземпляр, реализован потомкам track, progress, flag, scale, configuring, содержит структура всех представлений: форматирование разметки, отрисовка разметки, навешивание обработчиков. Там есть createElement

**Comment by webproject67** [comment]
[#63](https://github.com/webproject67/Slider/issues/63) [update](https://github.com/webproject67/Slider/pull/66)
