### ISSUE TITLE
Конфигурационная панель

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#67]
Конфигурационная панель должна управлять слайдером снаружи, а не быть одним из составляющих вида. Вообще конфигурационная панель может быть и одним из видов, но в рамках учебного проекта она должна им управлять именно снаружи. В требованиях есть пункт о том что должна быть возможность изменять значение слайдера снаружи, так вот конфигурационная панель в данном случае нужна как раз для демонстрации этого.

**Comment by webproject67** [comment]
Раньше не понял что значит снаружи, сейчас понял, вне MPV
[#67](https://github.com/webproject67/Slider/issues/67) [updated](https://github.com/webproject67/Slider/pull/69)

**Comment by Azmodan95** [comment]
Она должна быть вообще за пределами плагина, то есть где у тебя происходит создание инстанса плагина, вот этим инстансом она должна управлять прокидывая другой набор настроек, и достаточно чтобы реагировала только на изменение значений, остальные параметры в плагине не изменяются в процессе поэтому реагировать на них нет необходимости.

**Comment by webproject67** [comment]
[#67](https://github.com/webproject67/Slider/issues/67) [updated](https://github.com/webproject67/Slider/pull/72)

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Slider/blob/c97cbf807a734ceb2910a7eafc9cfaa7c2885a63/src/scripts/slider.js#L4
Смотри у тебя здесь создается инстанс, так вон конфигурационная панель должна именно этим инстансом управлять, а не быть внутри него. Она не должна генерировать ни каких событий, у слайдера должен быть какой-то метод для обновления, вот его она и должна вызвать передавая другой объект настроек.

**Comment by webproject67** [comment]
[#67](https://github.com/webproject67/Slider/issues/74) [updated](https://github.com/webproject67/Slider/pull/77)

**Comment by webproject67** [comment]
[#67](https://github.com/webproject67/Slider/issues/67) [updated](https://github.com/webproject67/Slider/pull/79)
