### ISSUE TITLE
Работа с DOM

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#71]
Сейчас очень часто встречается что обращение к dom элементом идет через children, parentElement и childNodes, достаточно плохо читаемо, к примеру `progress.children[0]` как вообще понять что это за элемент children[0]? И не очень надежна, так как порядок элементов и структура может поменяться и это уже работать не будет. Обращение к dom элементам должно быть либо с использованием ссылки, которую возвращает createElement либо использовать поиск по dom дереву. 
https://github.com/webproject67/Slider/blob/f885dd727cc98be6b25386d1349859b5fcdd2aad/src/scripts/components/view/View.ts#L144
https://github.com/webproject67/Slider/blob/f885dd727cc98be6b25386d1349859b5fcdd2aad/src/scripts/components/view/View.ts#L25
К примеру здесь ведь можно было бы использовать ссылку на которая у тебя уже хранится в свойстве класса.
https://github.com/webproject67/Slider/blob/f885dd727cc98be6b25386d1349859b5fcdd2aad/src/scripts/components/view/View.ts#L76

---

https://github.com/webproject67/Slider/blob/f885dd727cc98be6b25386d1349859b5fcdd2aad/src/scripts/components/view/View.ts#L176
Еще момент в данном случае же можно было использовать `classList.contains`, где-то у тебя он и используется, где-то подобные проверки делаются.

**Comment by webproject67** [comment]
[#71](https://github.com/webproject67/Slider/issues/71) [updated](https://github.com/webproject67/Slider/pull/73)
