### ISSUE TITLE
Валидация входных параметров

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#74]
Сейчас валидация некоторых параметров есть только на стороне конфигурационной панели, она должна быть и в самой модели, параметры эти параметры ведь ей могут прийти не только с конфигурационной панели, но и быть переданных при инициализации плагина. Не должно быть поломанного слайдера в случае некоренных параметров, нужно либо подставлять ближайшие валидные значения либо если нет такой возможно то генерировать ошибку.

**Comment by webproject67** [comment]
[#74](https://github.com/webproject67/Slider/issues/74) [updated](https://github.com/webproject67/Slider/pull/77)

**Comment by Azmodan95** [comment]
Сейчас дефолтные параметры переехали в модель, установка дефолтных параметров должна быть на уровне плагина.

**Comment by webproject67** [comment]
[#74](https://github.com/webproject67/Slider/issues/74) [updated](https://github.com/webproject67/Slider/pull/80)
