### ISSUE TITLE
Инкапсуляция данных

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#75]
https://github.com/webproject67/Slider/blob/c97cbf807a734ceb2910a7eafc9cfaa7c2885a63/src/scripts/components/model/Model.ts#L6
Не должно быть прямого доступа к свойствам класса с наружи, чтение/запись должны происходить только через методы класса. В данном случае state должно быть приватным свойством, а для его получения есть уже метод getState, так же если в свойстве хранится объект или массив всегда нужно возвращать его копию, так в js объекты/массивы передаются по ссылке, и если передавать эту ссылку на прямую то появится возможность изменять значение этого объекта/массива снаружи.

**Comment by webproject67** [comment]
[#75](https://github.com/webproject67/Slider/issues/75) [updated](https://github.com/webproject67/Slider/pull/76)

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/components/presenter/Presenter.ts#L6-L8
Эти свойства тоже должны быть приватными.
https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/components/model/Model.ts#L28
И я писал что если возвращается объект то должна возвращаться его копия, а не он сам, иначе появится возможно изменять его снаружи, исключением являются ссылки на html элементы, в данном случае, чтобы получить копию можно использовать рест оператор { ...this.state }

**Comment by webproject67** [comment]
[#75](https://github.com/webproject67/Slider/issues/75) [updated](https://github.com/webproject67/Slider/pull/79)

**Comment by Azmodan95** [comment]
https://github.com/webproject67/Slider/blob/3e031f0c7d9b965dfba04877ad17391c4610d8fa/src/scripts/components/model/Model.ts#L111
Один нюанс, здесь тоже надо копию передавать.

**Comment by webproject67** [comment]
[#75](https://github.com/webproject67/Slider/issues/75) [updated](https://github.com/webproject67/Slider/pull/82)

**Comment by webproject67** [comment]
[#75](https://github.com/webproject67/Slider/issues/75) [updated](https://github.com/webproject67/Slider/pull/82)
