### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#78]
https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/Slider.ts#L7
Для того чтобы обозначить, что параметр является не обязательным после названия параметры нужно ставить вопросительный знак
` constructor(main: HTMLElement, options?: object)`
Так же тип object вообще лучше не использовать так как он совместим так же с функциями и массивами, в данном случае лучше явно описать объект настроек. Если же нужно описать какой-то произвольный объект – то можно использовать `Record`, который принимает первым аргументов тип ключа, вторым тип свойства.

---
https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/components/view/View.ts#L167

Существуют типы событий MouseEvent и TouchEvent, в данном случае лучше их и использовать. А чтобы определять с каким типом события мы работаем можно создать type guard, к примеру:
```
function isMouseEvent(event: unknown): event is MouseEvent {
  return event instanceof MouseEvent;
}
```

https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/components/view/View.ts#L144
Использование type assertion лучше свести к минимуму и использовать его только там где без него действительно не обойтись

---

https://github.com/webproject67/Slider/blob/a8cc678b825a63f3126facb5e9cf5bac74d5723e/src/scripts/components/model/Model.ts#L31
В данном случае не совсем подходящая структура данных используется, ключи в одном массиве передаются, а значения в другом и они между собой не связанны, корректность работы гарантируется только при правильном порядке. И это невозможно нормально затипизировать, сейчас у тебя по этой причине используется явное приведение типов при установке значений. Лучше использовать более подходящую структуру к примеру объект `{ type: 'updateValue', value: 1 }` в этом случае появится возможно затипизировать передаваемые данные по дискриминанту к примеру:
```
type UpdateValue {
  type: 'updateValue';
  value: number;
}

type UpdateOrientation {
  type: 'updateOrientation';
  value: 'horizontal' | 'vertical'
}

type Update = UpdateValue | UpdateOrientation;
```
И при проверке свойства `type`, typescript уже будет значить какой тип данные находится в свойстве `value`

**Comment by webproject67** [comment]
[#78](https://github.com/webproject67/Slider/issues/78) [updated](https://github.com/webproject67/Slider/pull/81)

**Comment by Azmodan95** [comment]
Вернулась старая проблема с тем что вид подстраивается под модель, возможно она и тогда была решена не до конца. Смотри вид и модель должны быть независимыми единицами, предполагается что должна быть возможно заменить вид или модель, и для этого не нужно будет менять нечего глобально достаточно заменить вызываемые методы в презентере на другие. Сейчас же презентер вообще бессмысленный, так как модель и вид передает удобную друг для друга структуру данных и они вполне могут обойтись без него.
А теперь давай представим что у нас изменится интерфейс модели и структура данных которую сейчас передает вид ей уже не подойдет, как нам нужно будет передаваемые объекты видом адаптировать под новый интерфейс модели? И как нам понять если нам придет объект `{ toPercent: 1 }` что за событие произошло и что нам нужно обновить? Либо аналогичная ситуация в модели при обновлении состояние передается объект, как определить что это обновилось состояние модели, а не что-то еще?

---

https://github.com/webproject67/Slider/blob/3e031f0c7d9b965dfba04877ad17391c4610d8fa/src/scripts/components/view/View.ts#L213
Здесь можно MouseEvent, я предполагаю что проблема из-за этого места:
https://github.com/webproject67/Slider/blob/3e031f0c7d9b965dfba04877ad17391c4610d8fa/src/scripts/components/view/View.ts#L113-L115
`querySelectorAll` по умолчанию возвращает элементы типа `Element`, но не у всех элементов типа `Element` может быть событие `MouseEvent`, `querySelectorAll` может принимать дженерик аргумент передав его мы можем явно указать какого типа элементы мы пытаемся найти `querySelectorAll<HTMLDivElement>('div')`

---

https://github.com/webproject67/Slider/blob/3e031f0c7d9b965dfba04877ad17391c4610d8fa/src/scripts/components/view/View.ts#L190
Здесь точно нужен оператор `!`?

---

https://github.com/webproject67/Slider/blob/3e031f0c7d9b965dfba04877ad17391c4610d8fa/src/scripts/components/view/View.ts#L145-L152
Здесь, вместо того чтобы использовать оператор `!`, перед тем как передавать значение в метод `this.replaceCircle`, лучше сделать проверку не равна ли переменная `circle` `null`

**Comment by webproject67** [comment]
[#78](https://github.com/webproject67/Slider/issues/78) [updated](https://github.com/webproject67/Slider/pull/82)

**Comment by Azmodan95** [comment]
Почти все хорошо) Но по именам событий не понятно что конкретно произошло, к примеру посмотри какие названия событий у addEventListener, там из их названий ведь очевидно на какое событие мы подписываемся. А как понять что за событие к примеру "track"?

https://github.com/webproject67/Slider/blob/fb2f5b955d911675a29bfd36ae9b6f4e86c883a7/src/scripts/components/model/Model.ts#L107
И появилась новая проблема, почему теперь модель подстраивается под события конфигурационной панели? Слайдер вообще нечего не должен знать о способе обновления конфигурационной панели, конфигурационная панель должна сама генерировать нужные данные для обновления.

**Comment by webproject67** [comment]
[#78](https://github.com/webproject67/Slider/issues/78) [updated](https://github.com/webproject67/Slider/pull/85)
