### ISSUE TITLE
Мелкие недочеты

### ISSUE THREAD

**Issue by Azmodan95** [webproject67/Slider#84]
https://github.com/webproject67/Slider/blob/fb2f5b955d911675a29bfd36ae9b6f4e86c883a7/src/scripts/components/model/Model.ts#L42
Зачем инвертировать результат проверки? Можно ведь просто поменять проверку на равенство на проверку на не равенство
https://github.com/webproject67/Slider/blob/fb2f5b955d911675a29bfd36ae9b6f4e86c883a7/src/scripts/components/model/Model.ts#L43-L44
Зачем здесь приведение типов? И так ведь делается проверка на нужный тип.

---

Сейчас если передвинуть два бегунка на максимальное значение, то теряется возможность их перемещать.

**Comment by webproject67** [comment]
https://github.com/webproject67/Slider/blob/fb2f5b955d911675a29bfd36ae9b6f4e86c883a7/src/scripts/components/model/Model.ts#L42
Если state.min = 0, условие не выполнит, не запишет новое значение, также если state.scale = false, не удалит шкалу, если снять галку

[#84](https://github.com/webproject67/Slider/issues/84) [updated](https://github.com/webproject67/Slider/pull/86)
