### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Slider#90]
шаг - 33, максимальное значение 100.
![image](https://user-images.githubusercontent.com/47000555/149616423-b2763aa4-0548-4843-ab85-262800a628b0.png)
так же при клике не дает на максимальное значение попасть
https://user-images.githubusercontent.com/47000555/149616557-00737727-f964-4c2f-b763-82ee2dc0c3b8.mp4

Еще немного странно что при клике всегда летит правый ползунок. Левый вообще никак не реагирует, хотя по идее нужно перемещать ползунок в зависимости от положения к выбранному значению шкалы. 

https://user-images.githubusercontent.com/47000555/149616630-16b3b73e-113f-4eb0-a732-48a5fa2b59ec.mp4

Два ползунка прилипли к друг другу. Отлипнут только если с помощью шкалы кликнуть.

https://user-images.githubusercontent.com/47000555/149616717-7278f29c-8346-4209-a2af-9500674984bc.mp4

Скривилось положение. Значение шага 10.5
![image](https://user-images.githubusercontent.com/47000555/149616784-71f1ba92-abfe-47ee-8d78-589562ad79f3.png)

**Comment by webproject67** [comment]
1. не важно какой шаг будет, всегда дойдет до максимального значения, по умолчанию 100
---
2. исправил
---
3. у меня логика такая, при клике всегда правый ползунок летит, если меньше чем левый ползунок, то левый

https://user-images.githubusercontent.com/34152979/149650033-3b77c4a7-44d9-4723-ad02-943f96185ad3.mp4

---
4. исправил
---
5. шаг по умолчанию 1, это минимум и только целое число, зачем дробное число, исправил
---
[#90](https://github.com/webproject67/Slider/issues/90) [updated](https://github.com/webproject67/Slider/pull/93)

**Comment by sodiqit** [comment]
1. Не особо понял меня, я имел ввиду что значения друг на друга налезли.
3. Не особо практично, но ладно, в ТЗ про это ничего нет.

**Comment by sodiqit** [comment]
Закрою ишью
