### ISSUE TITLE
Именование 

### ISSUE THREAD

**Issue by sodiqit** [webproject67/Slider#91]
CAMELCASE разделяет слова между собой через `_`. То есть не `UPDATEMODELSTATE` а `UPDATE_MODEL_STATE`
![image](https://user-images.githubusercontent.com/47000555/149617725-22440a26-ac61-4b7f-9765-c345eea2b719.png)

**Comment by webproject67** [comment]
[#91](https://github.com/webproject67/Slider/issues/91) [updated](https://github.com/webproject67/Slider/pull/92)
